routes/web.php
<?php

Route::get('/', 'HomePageController@homepage');

Route::post('/', 'HomePageController@sendNotification');

Route::group(['namespace' => 'Admin', 'prefix' => 'admin'], function () {
    Route::group(['namespace' => 'Auth'], function () {
        Route::get('login', 'LoginController@showLoginForm');
        Route::post('login', 'LoginController@login');
        Route::post('password/email', 'ForgotPasswordController@sendResetLinkEmail');
        Route::get('password/reset', 'ForgotPasswordController@showLinkRequestForm');
        Route::post('password/reset', 'ResetPasswordController@reset');
        Route::get('password/reset/{token}', 'ResetPasswordController@showResetForm');
        Route::get('logout', 'LoginController@logout');
    });

    Route::group(['middleware' => ['auth']], function () {
        Route::get('/', function () {
            return view('layouts.admin');
        });

        Route::group(['as' => 'settings.', 'namespace' => 'Settings', 'prefix' => 'settings'], function () {
            Route::get('/default', ['as' => 'default.edit', 'uses' => 'DefaultSettingsController@edit']);
            Route::put('/default', ['as' => 'default.update', 'uses' => 'DefaultSettingsController@update']);
            Route::delete('/default/about_image',
                ['as' => 'default.about.image.destroy', 'uses' => 'DefaultSettingsController@aboutImageDestroy']);
            Route::resource('icons', 'IconController');
            Route::resource('images', 'ImagesController');

            Route::get('user', ['as' => 'user.edit', 'uses' => 'UserController@edit']);
            Route::put('user', ['as' => 'user.update', 'uses' => 'UserController@update']);
        });

        Route::resource('partners', 'PartnersController', [
            'except' => ['show'],
        ]);

        Route::resource('feedback', 'FeedbackController', [
            'except' => ['show'],
        ]);

        Route::resource('teachers', 'TeachersController', [
            'except' => ['show'],
        ]);

        Route::put('programs/{program}/status',
            ['as' => 'programs.status', 'uses' => 'ProgramsController@updateStatus']);
        Route::resource('programs', 'ProgramsController');
    });
});

app/Models/Program.php
<?php

namespace App\Models;

use App\Traits\ActiveAttributeTrait;
use App\Traits\IconAttributeTrait;
use Illuminate\Database\Eloquent\Model;

/**
 * App\Models\Program
 *
 * @property \App\Models\Icon $icon
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Models\ProgramItem[] $items
 * @property-write mixed $active
 * @mixin \Eloquent
 * @property int $id
 * @property string $name
 * @property int $icon_id
 * @property \Carbon\Carbon $created_at
 * @property \Carbon\Carbon $updated_at
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Program whereActive($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Program whereCreatedAt($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Program whereIconId($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Program whereId($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Program whereName($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Program whereUpdatedAt($value)
 */
class Program extends Model
{
    use ActiveAttributeTrait, IconAttributeTrait;
    protected $fillable = [
        'name',
        'icon',
        'active',
    ];
    
    public function items()
    {
        return $this->hasMany('App\Models\ProgramItem', 'program_id');
    }
    
    public function icon()
    {
        return $this->belongsTo('App\Models\Icon', 'icon_id');
    }
}

app/Http/Controllers/Admin/ProgramsController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\StoreProgramRequest;
use App\Models\Program;
use App\Models\ProgramItem;
use Illuminate\Http\Request;

class ProgramsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @param \Illuminate\Http\Request $request
     *
     * @return array|\Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        if ($request->ajax()) {
            return Program::with('items', 'items.icon')->get();
        }
        return view('admin.programs.index', [
            'programs' => Program::paginate(25),
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.programs.edit', [
            'program' => new Program()
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \App\Http\Requests\StoreProgramRequest $request
     *
     * @return \Illuminate\Http\Response
     */
    public function store(StoreProgramRequest $request)
    {
        $program = Program::create($request->all());

        if ($request->has('items')) {
            foreach ($request->input('items') as $item) {
                $program->items()->create($item);
            }
        }

        return response()->json([
            'redirect' => route('programs.index'),
        ]);
    }

    /**
     * @param Request $request
     * @param Program $program
     * @return $this
     */
    public function show(Request $request, Program $program)
    {
        if ($request->ajax()) {
            return $program->load('icon', 'items', 'items.icon');
        }
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  Program $program
     *
     * @return \Illuminate\Http\Response
     */
    public function edit(Program $program)
    {
        return view('admin.programs.edit', ['program' => $program]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \App\Http\Requests\StoreProgramRequest $request
     * @param  Program $program
     *
     * @return \Illuminate\Http\Response
     */
    public function update(StoreProgramRequest $request, Program $program)
    {
        $program->update($request->all());

        $programItems = array_keys($program->items->keyBy('id')->toArray());
        if ($request->has('items')) {
            foreach ($request->input('items') as $item) {
                $item['program_id'] = $program->id;
                if (isset($item['id'])) {
                    $programItem = ProgramItem::firstOrNew(['id' => $item['id']]);
                    $programItem->fill($item);
                    $programItem->save();
                    $programItemKey = array_search($programItem->id, $programItems);
                    if ($programItemKey !== null) {
                        unset($programItems[$programItemKey]);
                    }
                } else {
                    ProgramItem::create($item);
                }

            }
        }
        ProgramItem::destroy($programItems);

        return response()->json([
            'redirect' => route('programs.index'),
        ]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  Program $program
     *
     * @return array|\Illuminate\Http\Response
     */
    public function destroy(Program $program)
    {
        if ($program->delete()) {
            return ['message' => trans('messages.delete_successful', ['entity' => trans('entities.program')])];
        }
    }

    /**
     * Update status on resources in storage
     *
     * @param Request $request
     * @param Program $program
     */
    public function updateStatus(Request $request, Program $program)
    {
        if ($request->ajax() && $request->has('active')) {
            $program->update(['active' => $request->input('active')]);
        }
    }
}

resources/views/admin/programs/edit.blade.php
@extends('layouts.admin')

@section('title')
    @if($program->id)
        @lang('headers.programs.edit', ['program' => $program->name])
    @else
        @lang('headers.programs.create')
    @endif
@endsection

@section('breadcrump')
    <li><a href="{{ url('admin') }}"><span class="s7-home"></span></a></li>
    <li><a href="{{ route('programs.index') }}">@lang('menu.programs.index')</a></li>
    @if($program->id)
        <li class="active">@lang('headers.programs.edit', ['program' => $program->name])</li>
    @else
        <li class="active">@lang('headers.programs.create')</li>
    @endif
@endsection

@section('content')
    <div class="panel panel-default">
        <div class="panel-body">
            <program
                    action="{{ $program->id ? route('programs.update', ['program' => $program->id]) : route('programs.store') }}"
                    icon-src="{{ asset('assets/images/icons.svg') }}"
                    method="{{ $program->id ? 'PUT' : 'POST' }}"
                    @if ($program->id) :program-id="{{ $program->id }}" @endif
            ></program>
        </div>
    </div>

@endsection

resources/views/admin/programs/index.blade.php
@extends('layouts.admin')

@section('title')
    @lang('headers.programs.index')
@endsection

@section('action-panel')
    <a href="{{ route('programs.create') }}" class="btn btn-primary btn-sm">@lang('buttons.new')</a>
@endsection

@section('breadcrump')
    <li><a href="{{ url('admin') }}"><span class="s7-home"></span></a></li>
    <li class="active">@lang('headers.programs.index')</li>
@endsection

@section('content')
    <div class="row">
        <!--Responsive table-->
        <div class="col-sm-12">
            <div class="widget widget-fullwidth widget-small">
                <div class="">
                    <table class="table table-striped table-fw-widget table-hover">
                        <thead>
                        <tr>
                            <th width="5%">@lang('fields.icon')</th>
                            <th width="55%">@lang('fields.name')</th>
                            <th width="10%">@lang('fields.active')</th>
                            <th width="10%">@lang('fields.actions')</th>
                        </tr>
                        </thead>
                        <tbody class="no-border-x icons-list">
                        @forelse($programs as $program)

                            <tr>
                                <td class="icon-sm">
                                    <svg class="icon">
                                        <use xlink:href="{{ asset('assets/images/icons.svg') }}{{ $program->icon ? $program->icon->machine_name : '' }}"></use>
                                    </svg>
                                </td>
                                <td>
                                    {{ $program->name }}
                                </td>
                                <td>
                                    <switch-button name="active" :value="{{ $program->active }}"
                                                   id="active_{{ $program->id }}"
                                                   :switch-yes-no="true"
                                                   update-src="{{ route('programs.status', ['program' => $program->id]) }}"
                                    ></switch-button>
                                </td>
                                <td id="program-remove-{{ $program->id }}">
                                    <a href="{{ route('programs.edit', ['program' => $program->id]) }}">@lang('buttons.edit')</a>
                                    <a href="#" class="text-danger"
                                       data-toggle="confirmation"
                                       data-placement="left"
                                       data-container="#program-remove-{{ $program->id }}"
                                       data-btn-ok-label="@lang('buttons.remove')"
                                       data-btn-ok-class="btn-success"
                                       data-btn-cancel-label="@lang('buttons.cancel')"
                                       data-btn-cancel-class="btn-danger"
                                       data-remove="{{ route('programs.destroy', ['program' => $program->id]) }}"
                                       data-title="@lang('messages.remove_title')"
                                       data-content="@lang('messages.remove_item')"
                                    >@lang('buttons.delete')</a>
                                </td>
                            </tr>
                        @empty
                            <tr>
                                <td colspan="4">
                                    @lang('messages.no_programs')
                                </td>
                            </tr>
                        @endforelse
                        </tbody>
                    </table>
                </div>
            </div>
            <nav aria-label="Page navigation">
                {{ $programs->links() }}
            </nav>
        </div>
    </div>
@endsection