routes/web.php
<?php

Route::get('/', 'HomePageController@homepage');

Route::post('/', 'HomePageController@sendNotification');

Route::group(['namespace' => 'Admin', 'prefix' => 'admin'], function () {
    Route::group(['namespace' => 'Auth'], function () {
        Route::get('login', 'LoginController@showLoginForm');
        Route::post('login', 'LoginController@login');
        Route::post('password/email', 'ForgotPasswordController@sendResetLinkEmail');
        Route::get('password/reset', 'ForgotPasswordController@showLinkRequestForm');
        Route::post('password/reset', 'ResetPasswordController@reset');
        Route::get('password/reset/{token}', 'ResetPasswordController@showResetForm');
        Route::get('logout', 'LoginController@logout');
    });

    Route::group(['middleware' => ['auth']], function () {
        Route::get('/', function () {
            return view('layouts.admin');
        });

        Route::group(['as' => 'settings.', 'namespace' => 'Settings', 'prefix' => 'settings'], function () {
            Route::get('/default', ['as' => 'default.edit', 'uses' => 'DefaultSettingsController@edit']);
            Route::put('/default', ['as' => 'default.update', 'uses' => 'DefaultSettingsController@update']);
            Route::delete('/default/about_image',
                ['as' => 'default.about.image.destroy', 'uses' => 'DefaultSettingsController@aboutImageDestroy']);
            Route::resource('icons', 'IconController');
            Route::resource('images', 'ImagesController');

            Route::get('user', ['as' => 'user.edit', 'uses' => 'UserController@edit']);
            Route::put('user', ['as' => 'user.update', 'uses' => 'UserController@update']);
        });

        Route::resource('partners', 'PartnersController', [
            'except' => ['show'],
        ]);

        Route::resource('feedback', 'FeedbackController', [
            'except' => ['show'],
        ]);

        Route::resource('teachers', 'TeachersController', [
            'except' => ['show'],
        ]);

        Route::put('programs/{program}/status',
            ['as' => 'programs.status', 'uses' => 'ProgramsController@updateStatus']);
        Route::resource('programs', 'ProgramsController');
    });
});

resources/views/layouts/partials/nav_default.blade.php
<nav class="navbar navbar-default navbar-fixed-top am-top-header">
    <div class="container-fluid">
        <div class="navbar-header">
            <div class="page-title">
                <span>Dashboard</span>
            </div>
            <a href="#" class="am-toggle-left-sidebar navbar-toggle collapsed">
                <span
                        class="icon-bar">
                    <span></span>
                    <span></span>
                    <span></span>
                </span>
            </a>
            <a href="{{ url('admin') }}" class="navbar-brand"></a>
        </div>
        <a href="#"
           data-toggle="collapse"
           data-target="#am-navbar-collapse"
           class="am-toggle-top-header-menu collapsed">
            <span class="icon s7-angle-down"></span>
        </a>

        <div id="am-navbar-collapse" class="collapse navbar-collapse">
            <ul class="nav navbar-nav navbar-right am-user-nav">
                <li class="dropdown"><a href="#" data-toggle="dropdown" role="button" aria-expanded="false"
                                        class="dropdown-toggle"><span class="angle-down s7-angle-down"></span></a>
                    <ul role="menu" class="dropdown-menu">
                        <li><a href="{{ route('settings.user.edit') }}"><span
                                        class="icon s7-unlock"></span>@lang('auth.change_password')</a></li>
                        <li><a href="{{ url('admin/logout') }}"> <span class="icon s7-power"></span>@lang('auth.logout')
                            </a>
                        </li>
                    </ul>
                </li>
            </ul>
            <ul class="nav navbar-nav am-nav-right">
                <li><a href="{{ url('/') }}">@lang('menu.homepage')</a></li>
                <li class="dropdown">
                    <a href="#" data-toggle="dropdown" role="button" aria-expanded="false"
                       class="dropdown-toggle">@lang('menu.settings')
                        <span class="angle-down s7-angle-down"></span>
                    </a>
                    <ul role="menu" class="dropdown-menu">
                        <li><a href="{{ route('settings.default.edit') }}">@lang('menu.default_settings')</a></li>
                        <li><a href="{{ route('settings.icons.index') }}">@lang('menu.icons')</a></li>
                        <li><a href="{{ route('settings.images.index') }}">@lang('menu.images')</a></li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</nav>

resources/views/layouts/partials/nav_left.blade.php
<div class="am-left-sidebar am-left-sidebar--clic">
    <div class="content">
        <div class="am-logo"></div>
        <ul class="sidebar-elements">
            <li><a href="{{ route('partners.index') }}"><i class="icon s7-cash"></i><span>@lang('menu.partners.index')</span></a></li>
            <li><a href="{{ route('feedback.index') }}"><i class="icon s7-comment"></i><span>@lang('menu.feedback.index')</span></a></li>
            <li><a href="{{ route('teachers.index') }}"><i class="icon s7-users"></i><span>@lang('menu.teachers.index')</span></a></li>
            <li><a href="{{ route('programs.index') }}"><i class="icon s7-study"></i><span>@lang('menu.programs.index')</span></a></li>
            {{--<li><a href="{{ url('tasks') }}"><i class="icon s7-check"></i><span>Tasks</span></a></li>--}}
            {{--<li><a href="{{ url('projects') }}"><i class="icon s7-photo-gallery"></i><span>Projects</span></a></li>--}}
            {{--<li class="parent"><a href="#"><i class="icon s7-user"></i><span>Contacts</span></a>--}}
            {{--<ul class="sub-menu">--}}
            {{--<li><a href="{{ route('clients.index') }}">Clients</a></li>--}}
            {{--<li><a href="{{ route('client-contacts.index') }}">Client Contacts</a></li>--}}
            {{--<li><a href="{{ route('addresses.index') }}">Addresses</a></li>--}}
            {{--</ul>--}}
            {{--</li>--}}
            {{--<li><a href="{{ url('timesheets') }}"><i class="icon s7-timer"></i><span>Time</span></a></li>--}}
            {{--<li><a href="{{ url('team-members') }}"><i class="icon s7-users"></i><span>Team</span></a></li>--}}
            {{--<li><a href="{{ url('invoices') }}"><i class="icon s7-copy-file"></i><span>Invoices</span></a></li>--}}
            {{--<li class="parent"><a href="#"><i class="icon s7-piggy"></i><span>Cashflow</span></a>--}}
            {{--<ul class="sub-menu">--}}
            {{--<li><a href="{{ url('cashflow') }}">Cashflow</a></li>--}}
            {{--<li><a href="{{ url('income') }}">Income</a></li>--}}
            {{--<li><a href="{{ url('expenses') }}">Expenses</a></li>--}}
            {{--</ul>--}}
            {{--</li>--}}
            {{--<li><a href="{{ url('reports') }}"><i class="icon s7-folder"></i><span>Reports</span></a></li>--}}
            {{--<li><a href="{{ url('folders') }}"><i class="icon s7-folder"></i><span>Folders</span></a></li>--}}
        </ul>
        <!--Sidebar bottom content-->
    </div>
</div>