routes/web.php
<?php

Route::get('/', 'HomePageController@homepage');

Route::post('/', 'HomePageController@sendNotification');

Route::group(['namespace' => 'Admin', 'prefix' => 'admin'], function () {
    Route::group(['namespace' => 'Auth'], function () {
        Route::get('login', 'LoginController@showLoginForm');
        Route::post('login', 'LoginController@login');
        Route::post('password/email', 'ForgotPasswordController@sendResetLinkEmail');
        Route::get('password/reset', 'ForgotPasswordController@showLinkRequestForm');
        Route::post('password/reset', 'ResetPasswordController@reset');
        Route::get('password/reset/{token}', 'ResetPasswordController@showResetForm');
        Route::get('logout', 'LoginController@logout');
    });

    Route::group(['middleware' => ['auth']], function () {
        Route::get('/', function () {
            return view('layouts.admin');
        });

        Route::group(['as' => 'settings.', 'namespace' => 'Settings', 'prefix' => 'settings'], function () {
            Route::get('/default', ['as' => 'default.edit', 'uses' => 'DefaultSettingsController@edit']);
            Route::put('/default', ['as' => 'default.update', 'uses' => 'DefaultSettingsController@update']);
            Route::delete('/default/about_image',
                ['as' => 'default.about.image.destroy', 'uses' => 'DefaultSettingsController@aboutImageDestroy']);
            Route::resource('icons', 'IconController');
            Route::resource('images', 'ImagesController');

            Route::get('user', ['as' => 'user.edit', 'uses' => 'UserController@edit']);
            Route::put('user', ['as' => 'user.update', 'uses' => 'UserController@update']);
        });

        Route::resource('partners', 'PartnersController', [
            'except' => ['show'],
        ]);

        Route::resource('feedback', 'FeedbackController', [
            'except' => ['show'],
        ]);

        Route::resource('teachers', 'TeachersController', [
            'except' => ['show'],
        ]);

        Route::put('programs/{program}/status',
            ['as' => 'programs.status', 'uses' => 'ProgramsController@updateStatus']);
        Route::resource('programs', 'ProgramsController');
    });
});

app/Models/Icon.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

/**
 * App\Models\Icon
 *
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Models\ProgramItem[] $programItems
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Models\Program[] $programs
 * @property-write mixed $machine_name
 * @mixin \Eloquent
 * @property int $id
 * @property string $name
 * @property string $file_name
 * @property bool $processed
 * @property \Carbon\Carbon $created_at
 * @property \Carbon\Carbon $updated_at
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Icon whereCreatedAt($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Icon whereFileName($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Icon whereId($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Icon whereMachineName($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Icon whereName($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Icon whereProcessed($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Icon whereUpdatedAt($value)
 */
class Icon extends Model
{
    protected $fillable = [
        'name',
        'machine_name',
        'file_name',
        'processed',
    ];

    public function programs()
    {
        return $this->hasMany('App\Models\Program', 'icon_id');
    }

    public function programItems()
    {
        return $this->hasMany('App\Models\ProgramItem', 'icon_id');
    }

    public function setMachineNameAttribute($value)
    {
        $this->attributes['machine_name'] = '#icon-' . $value;
    }
}

app/Http/Controllers/Admin/Settings/DefaultSettingsController.php
<?php

namespace App\Http\Controllers\Admin\Settings;

use App\Http\Controllers\Controller;
use App\Http\Requests\StoreDefaultSettingsRequest;
use App\Models\Variable;
use App\Traits\ProcessImageTrait;
use Illuminate\Support\Facades\Storage;

class DefaultSettingsController extends Controller
{
    use ProcessImageTrait;
    /**
     * @var string
     */
    protected $aboutImage = 'images/default/about.jpg';
    /**
     * @var string
     */
    protected $logoPath = 'images/default/';

    /**
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function edit()
    {
        return view('admin.settings.default.edit', [
            'variables' => Variable::all()->pluck('value', 'key')->toArray(),
        ]);
    }

    /**
     * Update default settings
     *
     * @param StoreDefaultSettingsRequest $request
     *
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(StoreDefaultSettingsRequest $request)
    {
        $input = $request->except(['image_file', 'crop_data', '_method', '_token', 'label']);

        foreach ($input as $key => $value) {
            Variable::firstOrNew(['key' => $key])->fill(['value' => $value ?? ''])->save();
        }

        if ($request->hasFile('image_file')) {
            $file = $request->file('image_file');
        }
        if ($request->has('crop_data')) {
            if (empty($file) && Storage::exists($this->aboutImage)) {
                $file = Storage::get($this->aboutImage);
            }
            $crop = json_decode($request->input('crop_data'), true);
            if (!empty($file)) {
                $aboutImage = $this->processImage($file, $crop, 'jpg');
                Storage::put($this->aboutImage, $aboutImage->__toString());
                Variable::firstOrNew(['key' => 'about_image'])->fill(['value' => $this->aboutImage])->save();
            }
        }

        if ($request->hasFile('label')) {
            $label = $request->file('label');
            $logoSm = \Image::make($label)->resize(60, null, function ($constraint) {
                $constraint->aspectRatio();
            })->encode('png');
            $file_name = 'logo-primary.'.$label->extension();
            $label->storeAs($this->logoPath, $file_name);
            Variable::firstOrNew(['key' => 'label'])->fill(['value' => $this->logoPath.$file_name])->save();
            Storage::put($this->logoPath.'logo.png', $logoSm->__toString());
        }

        return back()->with('message',
            trans('messages.edit_successful', ['entity' => trans('entities.default_settings')]));;

    }

    /**
     * Delete about image
     *
     * @return array|\Illuminate\Http\RedirectResponse
     */
    public function aboutImageDestroy()
    {
        if ($variable = Variable::where('key', 'about_image')->first()) {
            if (Storage::exists($variable->value)) {
                Storage::delete($variable->value);
            }
            $variable->delete();
        }

        return [
            'message' => trans('messages.delete_successful', ['entity' => trans('entities.about_image')]),
            'redirect' => route('settings.default.edit'),
        ];
    }
}

app/Http/Controllers/Admin/Settings/IconController.php
<?php

namespace App\Http\Controllers\Admin\Settings;

use App\Http\Controllers\Controller;
use App\Http\Requests\StoreIconRequest;
use App\Jobs\UpdateIcons;
use App\Models\Icon;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;

class IconController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @param \Illuminate\Http\Request $request
     *
     * @return array|\Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        if ($request->ajax()) {
            return Icon::all();
        }
        
        return view('admin.settings.icons.index', [
            'icons' => Icon::paginate(25),
        ]);
    }
    
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.settings.icons.edit', [
            'icon' => new Icon(),
        ]);
    }
    
    /**
     * Store a newly created resource in storage.
     *
     * @param  \App\Http\Requests\StoreIconRequest $request
     *
     * @return \Illuminate\Http\Response
     */
    public function store(StoreIconRequest $request)
    {
        $icon = Icon::create($request->all());
        if ($request->hasFile('svg')) {
            $file = $request->file('svg');
            $file_name = $request->input('machine_name') . '.' . $file->extension();
            
            $file->storeAs('images/icons', $file_name);
            
            $icon->update(['file_name' => $file_name]);
        }
        
        $job = (new UpdateIcons($icon))
            ->delay(Carbon::now()->addMinutes(1));
        
        dispatch($job);
        
        return redirect()->route('settings.icons.index')->with('message',
            trans('messages.create_successful', ['entity' => trans('entities.icon')]));
    }
    
    /**
     * Show the form for editing the specified resource.
     *
     * @param  Icon $icon
     *
     * @return \Illuminate\Http\Response
     */
    public function edit(Icon $icon)
    {
        return view('admin.settings.icons.edit', [
            'icon' => $icon,
        ]);
    }
    
    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  Icon                     $icon
     *
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Icon $icon)
    {
        if ($request->hasFile('svg')) {
            $file = $request->file('svg');
            
            $file->storeAs('images/icons', $icon->file_name);
            $icon->update(['processed' => false]);
            $job = (new UpdateIcons($icon))
                ->delay(Carbon::now()->addMinutes(1));
            
            dispatch($job);
        }
        $icon->update($request->all());
        
        return redirect()->route('settings.icons.index')->with('message',
            trans('messages.edit_successful', ['entity' => trans('entities.icon')]));
        
    }
    
    /**
     * Remove the specified resource from storage.
     *
     * @param  Icon $icon
     *
     * @return array|\Illuminate\Http\Response
     */
    public function destroy(Icon $icon)
    {
        $file_name = 'images/icons' . $icon->file_name;
        if ($icon->delete()) {
            Storage::delete($file_name);
            
            return ['message' => trans('messages.delete_successful', ['entity' => trans('entities.icon')])];
        }
    }
}

app/Http/Controllers/Admin/Settings/ImagesController.php
<?php

namespace App\Http\Controllers\Admin\Settings;

use App\Http\Controllers\Controller;
use App\Http\Requests\StoreImagesRequest;
use App\Http\Requests\UpdateImagesRequest;
use App\Models\Image;
use App\Traits\ProcessImageTrait;
use Illuminate\Http\Request;
use Storage;

class ImagesController extends Controller
{
    use ProcessImageTrait;

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('admin.settings.images.index', [
            'images' => Image::paginate(25),
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.settings.images.edit', [
            'image' => new Image()
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \App\Http\Requests\StoreImagesRequest $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreImagesRequest $request)
    {
        $input = $request->all();

        if ($request->hasFile('image_file')) {
            $file = $request->file('image_file');
        }
        if ($request->has('crop_data')) {
            $crop = json_decode($request->input('crop_data'), true);
            if (!empty($file)) {
                $input['image'] = $this->processImage($file, $crop);
            }
        }
        Image::create($input);

        return redirect()->route('settings.images.index')->with('message',
            trans('messages.create_successful', ['entity' => trans('entities.image')]));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Image $image
     * @return \Illuminate\Http\Response
     */
    public function edit(Image $image)
    {
        return view('admin.settings.images.edit', [
            'image' => $image
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  UpdateImagesRequest $request
     * @param  \App\Models\Image $image
     * @return mixed|\Illuminate\Http\Response
     */
    public function update(UpdateImagesRequest $request, Image $image)
    {
        $input = $request->all();

        if ($request->hasFile('image_file')) {
            $file = $request->file('image_file');
        }
        if ($request->has('crop_data')) {
            if (empty($file)) {
                $url = public_path($image->image->url());
                if (Storage::exists($url)) {
                    $file = $url;
                }
            }
            $crop = json_decode($request->input('crop_data'), true);
            if (!empty($file)) {
                $input['image'] = $this->processImage($file, $crop);
            }
        }

        $image->update($input);

        if ($request->ajax()) {
            return $image;
        }

        return redirect()->route('settings.images.index')->with('message',
            trans('messages.edit_successful', ['entity' => trans('entities.image')]));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Image $image
     * @return mixed|\Illuminate\Http\Response
     */
    public function destroy(Image $image)
    {
        if ($image->delete()) {
            return ['message' => trans('messages.delete_successful', ['entity' => trans('entities.image')])];
        }
    }
}

app/Http/Controllers/Admin/Settings/UserController.php
<?php
/**
 * Created by PhpStorm.
 * User: rostislav
 * Date: 06.03.17
 * Time: 12:12
 */

namespace App\Http\Controllers\Admin\Settings;

use App\Http\Controllers\Controller;
use App\Http\Requests\UpdateUserRequest;
use Illuminate\Support\Str;

class UserController extends Controller
{
    public function edit()
    {
        return view('admin.settings.user.edit');
    }

    public function update(UpdateUserRequest $request)
    {
        $password = $request->input('password');
        $user = \Auth::user();
        $user->forceFill([
            'password'       => bcrypt($password),
            'remember_token' => Str::random(60),
        ])->save();

        \Auth::guard()->login($user);

        return back()->with('message',
            trans('messages.edit_successful', ['entity' => trans('entities.user')]));
    }
}

resources/views/admin/settings/icons/edit.blade.php
@extends('layouts.admin')

@section('title')
    @if($icon->id)
        @lang('headers.icons.edit', ['icon' => $icon->name])
    @else
        @lang('headers.icons.create')
    @endif
@endsection

@section('breadcrump')
    <li><a href="{{ url('admin') }}"><span class="s7-home"></span></a></li>
    <li><a href="{{ route('settings.icons.index') }}">@lang('menu.icons')</a></li>
    @if($icon->id)
        <li class="active">@lang('headers.icons.edit', ['icon' => $icon->name])</li>
    @else
        <li class="active">@lang('headers.icons.create')</li>
    @endif
@endsection

@section('content')
    <div class="panel panel-default">
        <div class="panel-body">
            <form method="POST"
                  action="{{ $icon->id ? route('settings.icons.update', ['icon' => $icon->id]) : route('settings.icons.store') }}"
                  enctype="multipart/form-data">
                @if($icon->id)
                    {{ method_field('PUT') }}
                @endif
                {{ csrf_field() }}
                <div class="row">
                    <div class="col-md-6">
                        <div class="panel panel-default">
                            <div class="panel-body">
                                <div class="form-group {{ $errors->has('name') ? ' has-error' : '' }}">
                                    <label for="name">@lang('fields.name')</label>
                                    <input type="text" id="name" name="name" class="form-control"
                                           value="{{ old('name') ?: $icon->name }}">
                                    @if ($errors->has('name'))
                                        <small class="help-block">
                                            {{ $errors->first('name') }}
                                        </small>
                                    @endif
                                </div>

                                <div class="form-group {{ $errors->has('machine_name') ? ' has-error' : '' }}">
                                    <label for="machine_name">@lang('fields.machine_name')</label>
                                    @if(!$icon->id)
                                        <div class="input-group">
                                            <div class="input-group-addon">#icon-</div>
                                            <input type="text" id="machine_name" name="machine_name"
                                                   class="form-control"
                                                   value="{{ old('machine_name') ?: $icon->machine_name }}">
                                        </div>
                                        @if ($errors->has('machine_name'))
                                            <small class="help-block">
                                                {{ $errors->first('machine_name') }}
                                            </small>
                                        @endif
                                    @else
                                        <p class="form-control-static">{{ $icon->machine_name }}</p>
                                    @endif
                                </div>

                                <div class="form-group {{ $errors->has('svg') ? ' has-error' : '' }}">
                                    <label for="svg">@lang('fields.svg')</label>
                                    <input type="file" id="svg" name="svg" class="form-control" accept=".svg"
                                           value="{{ old('svg') ?: ''}}">
                                    @if ($errors->has('svg'))
                                        <small class="help-block">
                                            {{ $errors->first('svg') }}
                                        </small>
                                    @endif
                                </div>
                                <div class="text-right">
                                    <input type="submit" value="@lang('buttons.save')" class="btn btn-primary">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
@endsection

resources/views/admin/settings/icons/index.blade.php
@extends('layouts.admin')

@section('title')
    @lang('headers.icons.index')
@endsection

@section('action-panel')
    <a href="{{ route('settings.icons.create') }}" class="btn btn-primary btn-sm">@lang('buttons.new')</a>
@endsection

@section('breadcrump')
    <li><a href="{{ url('admin') }}"><span class="s7-home"></span></a></li>
    <li class="active">@lang('headers.icons.index')</li>
@endsection

@section('content')
    @if($icons->contains('processed', false))
        <div role="alert" class="alert alert-warning alert-dismissible">
            <button type="button" data-dismiss="alert" aria-label="Close" class="close"><span aria-hidden="true"
                                                                                              class="s7-close"></span>
            </button>
            <span class="icon s7-check"></span>@lang('messages.icons_on_processed')
        </div>
    @endif
    <div class="row">
        <!--Responsive table-->
        <div class="col-sm-12">
            <div class="widget widget-fullwidth widget-small">
                <div class="table-responsive noSwipe">
                    <table class="table table-striped table-fw-widget table-hover">
                        <thead>
                        <tr>
                            <th width="5%">@lang('fields.icon')</th>
                            <th width="55%">@lang('fields.name')</th>
                            <th>@lang('fields.processed')</th>
                            <th width="10%">@lang('fields.actions')</th>
                        </tr>
                        </thead>
                        <tbody class="no-border-x icons-list">
                        @forelse($icons as $icon)
                            <tr>
                                <td class="icon-sm">
                                    <svg class="icon">
                                        <use xlink:href="{{ asset('assets/images/icons.svg') }}{{ $icon->machine_name }}"></use>
                                    </svg></td>
                                <td>{{ $icon->name }}</td>
                                <td>{{ $icon->processed ? trans('messages.yes') : trans('messages.no') }}</td>
                                <td id="icon-remove-{{ $icon->id }}">
                                    <a href="{{ route('settings.icons.edit', ['icon' => $icon->id]) }}">@lang('buttons.edit')</a>
                                    <a href="#" class="text-danger"
                                       data-toggle="confirmation"
                                       data-placement="left"
                                       data-container="#icon-remove-{{ $icon->id }}"
                                       data-btn-ok-label="@lang('buttons.remove')"
                                       data-btn-ok-class="btn-success"
                                       data-btn-cancel-label="@lang('buttons.cancel')"
                                       data-btn-cancel-class="btn-danger"
                                       data-remove="{{ route('settings.icons.destroy', ['icon' => $icon->id]) }}"
                                       data-title="@lang('messages.remove_title')"
                                       data-content="@lang('messages.remove_item')"
                                    >@lang('buttons.delete')</a>
                                </td>
                            </tr>
                        @empty
                            <tr>
                                <td colspan="4">
                                    @lang('messages.no_icons')
                                </td>
                            </tr>
                        @endforelse
                        </tbody>
                    </table>
                </div>
            </div>
            <nav aria-label="Page navigation">
                {{ $icons->links() }}
            </nav>
        </div>
    </div>
@endsection